# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    configmap.yaml                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ctragula <ctragula@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/02/22 15:55:29 by kemaritsu         #+#    #+#              #
#    Updated: 2021/04/16 16:05:23 by ctragula         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: metallb-system
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.99.120/32
