# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    ft_services.yaml                                   :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kemaritsu <kemaritsu@student.42.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/02/22 15:55:42 by kemaritsu         #+#    #+#              #
#    Updated: 2021/02/22 15:55:47 by kemaritsu        ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Namespace
metadata:
  name: services
