apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  labels:
    app: ftps
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.120
  selector:
    app: ftps
  ports:
    - protocol: TCP
      port: 21
      targetPort: 21
      name: ftps
    - protocol: TCP
      port: 30021
      targetPort: 30021
      name: ftp-passive
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-dp
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps
        - containerPort: 30021
          name: ftp-passive
