apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
  annotations: 
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: phpmyadmin
  type: LoadBalancer
  loadBalancerIP: 192.168.99.120
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: pma_image
        imagePullPolicy: Never
        resources:
          limits:
        ports:
        - containerPort: 5000