apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations: 
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  ports:
    - port: 5050
      targetPort: 5050
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
  loadBalancerIP: 192.168.99.120
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - name: wordpress
        image: wp_image
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        imagePullPolicy: Never
        resources:
          limits: 
        ports:
        - containerPort: 5050
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
