# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    influx_volume.yaml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ctragula <ctragula@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/04/07 18:27:07 by ctragula          #+#    #+#              #
#    Updated: 2021/04/07 18:28:30 by ctragula         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-influxdb
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
